version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true
